/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s262_1
#  OS:                Linux x86_64(Host ID compute-0-10.local)
#  Generated on:      Wed May 29 14:19:13 2013
#  Design:            MultiCell
#  Command:           saveNetlist parser_test_leafs.v -onlyLeafCell
###############################################################
*/
module heaterdriver (
	HeaterP, 
	HeaterN, 
	En);
   output HeaterP;
   output HeaterN;
   input En;
endmodule

module rxblock (
	testInB, 
	testInA, 
	pdB_p, 
	pdB_n, 
	pdB_dum_p, 
	pdB_dum_n, 
	pdA_p, 
	pdA_n, 
	pdA_dum_p, 
	pdA_dum_n, 
	outB, 
	outA, 
	clockP, 
	cfgB5, 
	cfgB4, 
	cfgB3, 
	cfgB2, 
	cfgB1, 
	cfgB0, 
	cfgA5, 
	cfgA4, 
	cfgA3, 
	cfgA2, 
	cfgA1, 
	cfgA0);
   input testInB;
   input testInA;
   input pdB_p;
   input pdB_n;
   input pdB_dum_p;
   input pdB_dum_n;
   input pdA_p;
   input pdA_n;
   input pdA_dum_p;
   input pdA_dum_n;
   output outB;
   output outA;
   input clockP;
   input [7:0] cfgB5;
   input [7:0] cfgB4;
   input [7:0] cfgB3;
   input [7:0] cfgB2;
   input [7:0] cfgB1;
   input [5:0] cfgB0;
   input [7:0] cfgA5;
   input [7:0] cfgA4;
   input [7:0] cfgA3;
   input [7:0] cfgA2;
   input [7:0] cfgA1;
   input [5:0] cfgA0;
endmodule

module ddr_mod_driver (
	in_o, 
	in_e, 
	clkTx, 
	cathode, 
	anode, 
	EnD, 
	EnC, 
	EnB, 
	EnBP, 
	EnA, 
	Dpulse, 
	DdelayC, 
	DdelayB, 
	DdelayA);
   input in_o;
   input in_e;
   input clkTx;
   output cathode;
   output anode;
   input [3:0] EnD;
   input [3:0] EnC;
   input [3:0] EnB;
   input EnBP;
   input [3:0] EnA;
   input [3:0] Dpulse;
   input [3:0] DdelayC;
   input [3:0] DdelayB;
   input [3:0] DdelayA;
endmodule

module XOR3_X2M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module XOR3_X1M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module XOR2_X3M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XOR2_X2M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XOR2_X1P4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XOR2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XOR2_X0P7M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XOR2_X0P5M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XNOR2_X3M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XNOR2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XNOR2_X0P7M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module XNOR2_X0P5M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module TIELO_X1M_A12TR (
	Y);
   output Y;
endmodule

module TIEHI_X1M_A12TR (
	Y);
   output Y;
endmodule

module SDFFRPQ_X4M_A12TR (
	SI, 
	SE, 
	R, 
	Q, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output Q;
   input D;
   input CK;
endmodule

module SDFFRPQ_X2M_A12TR (
	SI, 
	SE, 
	R, 
	Q, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output Q;
   input D;
   input CK;
endmodule

module SDFFRPQ_X1M_A12TR (
	SI, 
	SE, 
	R, 
	Q, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output Q;
   input D;
   input CK;
endmodule

module SDFFRPQ_X0P5M_A12TR (
	SI, 
	SE, 
	R, 
	Q, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output Q;
   input D;
   input CK;
endmodule

module SDFFRPQN_X3M_A12TR (
	SI, 
	SE, 
	R, 
	QN, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output QN;
   input D;
   input CK;
endmodule

module SDFFRPQN_X2M_A12TR (
	SI, 
	SE, 
	R, 
	QN, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output QN;
   input D;
   input CK;
endmodule

module SDFFRPQN_X1M_A12TR (
	SI, 
	SE, 
	R, 
	QN, 
	D, 
	CK);
   input SI;
   input SE;
   input R;
   output QN;
   input D;
   input CK;
endmodule

module OR3_X1M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module OR2_X8M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module OR2_X3M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module OR2_X2M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module OR2_X1P4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module OR2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module OAI31_X1P4M_A12TR (
	Y, 
	B0, 
	A2, 
	A1, 
	A0);
   output Y;
   input B0;
   input A2;
   input A1;
   input A0;
endmodule

module OAI31_X1M_A12TR (
	Y, 
	B0, 
	A2, 
	A1, 
	A0);
   output Y;
   input B0;
   input A2;
   input A1;
   input A0;
endmodule

module OAI2XB1_X4M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module OAI2XB1_X2M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module OAI2XB1_X1M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module OAI22_X1M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module OAI221_X3M_A12TR (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21_X4M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21_X3M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21_X1P4M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21_X1M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21_X0P7M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module OAI21B_X2M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module OA21_X3M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module NOR3_X4M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X3A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X2M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X1M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X1A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X0P7M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR3_X0P5M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NOR2_X4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X2M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X2A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X1P4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X1P4A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X1A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X0P7A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2_X0P5M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NOR2XB_X3M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NOR2XB_X2M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NOR2XB_X1P4M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NOR2XB_X1M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NOR2B_X3M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NOR2B_X2M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NOR2B_X1P4M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NOR2B_X1M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NOR2B_X0P7M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NOR2B_X0P5M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NAND4_X2M_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module NAND4_X2A_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module NAND4_X1M_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module NAND4_X1A_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module NAND4_X0P5M_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module NAND3_X2M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X2A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X1P4M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X1P4A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X1M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X1A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3_X0P7A_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module NAND3XXB_X2M_A12TR (
	Y, 
	CN, 
	B, 
	A);
   output Y;
   input CN;
   input B;
   input A;
endmodule

module NAND3XXB_X1M_A12TR (
	Y, 
	CN, 
	B, 
	A);
   output Y;
   input CN;
   input B;
   input A;
endmodule

module NAND3XXB_X0P7M_A12TR (
	Y, 
	CN, 
	B, 
	A);
   output Y;
   input CN;
   input B;
   input A;
endmodule

module NAND3XXB_X0P5M_A12TR (
	Y, 
	CN, 
	B, 
	A);
   output Y;
   input CN;
   input B;
   input A;
endmodule

module NAND2_X4A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X3A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X2M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X2A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X1P4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X1P4A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X1A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X0P7A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X0P5M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2_X0P5A_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module NAND2XB_X3M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NAND2XB_X2M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NAND2XB_X1P4M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NAND2XB_X1M_A12TR (
	Y, 
	BN, 
	A);
   output Y;
   input BN;
   input A;
endmodule

module NAND2B_X1P4M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NAND2B_X1M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module NAND2B_X0P5M_A12TR (
	Y, 
	B, 
	AN);
   output Y;
   input B;
   input AN;
endmodule

module MXT4_X2M_A12TR (
	Y, 
	S1, 
	S0, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input S1;
   input S0;
   input D;
   input C;
   input B;
   input A;
endmodule

module MXT4_X1M_A12TR (
	Y, 
	S1, 
	S0, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input S1;
   input S0;
   input D;
   input C;
   input B;
   input A;
endmodule

module MXT2_X1M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXT2_X0P7M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXT2_X0P5M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXIT2_X3M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXIT2_X2M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXIT2_X1M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXIT2_X0P7M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MXIT2_X0P5M_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MX2_X1P4B_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module MX2_X1B_A12TR (
	Y, 
	S0, 
	B, 
	A);
   output Y;
   input S0;
   input B;
   input A;
endmodule

module LATRQ_X2M_A12TR (
	RN, 
	Q, 
	G, 
	D);
   input RN;
   output Q;
   input G;
   input D;
endmodule

module LATRQ_X1M_A12TR (
	RN, 
	Q, 
	G, 
	D);
   input RN;
   output Q;
   input G;
   input D;
endmodule

module LATRPQN_X2M_A12TR (
	R, 
	QN, 
	G, 
	D);
   input R;
   output QN;
   input G;
   input D;
endmodule

module LATQ_X3M_A12TR (
	Q, 
	G, 
	D);
   output Q;
   input G;
   input D;
endmodule

module LATQ_X1M_A12TR (
	Q, 
	G, 
	D);
   output Q;
   input G;
   input D;
endmodule

module LATQ_X0P5M_A12TR (
	Q, 
	G, 
	D);
   output Q;
   input G;
   input D;
endmodule

module LATQN_X2M_A12TR (
	QN, 
	G, 
	D);
   output QN;
   input G;
   input D;
endmodule

module INV_X9M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X7P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X6M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X6B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X5B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X4M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X3P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X3P5B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X3M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X3B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X2P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X2B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X1P7M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X1P4B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X1M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X1B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X16M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X13M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X13B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X11M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X0P8M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X0P7M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X0P6M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module INV_X0P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module FILLDGCAP8_A12TR ();
endmodule

module FILLDGCAP64_A12TR ();
endmodule

module FILLDGCAP32_A12TR ();
endmodule

module FILLDGCAP16_A12TR ();
endmodule

module FILL4_A12TR ();
endmodule

module FILL2_A12TR ();
endmodule

module FILL1_A12TR ();
endmodule

module DLY4_X0P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DLY2_X0P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DLY2S4_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DLY2S3_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DLY2S2_X3M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DLY2S1_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module DFFSQ_X4M_A12TR (
	SN, 
	Q, 
	D, 
	CK);
   input SN;
   output Q;
   input D;
   input CK;
endmodule

module DFFSQ_X1M_A12TR (
	SN, 
	Q, 
	D, 
	CK);
   input SN;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQ_X4M_A12TR (
	R, 
	Q, 
	D, 
	CK);
   input R;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQ_X3M_A12TR (
	R, 
	Q, 
	D, 
	CK);
   input R;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQ_X2M_A12TR (
	R, 
	Q, 
	D, 
	CK);
   input R;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQ_X1M_A12TR (
	R, 
	Q, 
	D, 
	CK);
   input R;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQ_X0P5M_A12TR (
	R, 
	Q, 
	D, 
	CK);
   input R;
   output Q;
   input D;
   input CK;
endmodule

module DFFRPQN_X3M_A12TR (
	R, 
	QN, 
	D, 
	CK);
   input R;
   output QN;
   input D;
   input CK;
endmodule

module DFFRPQN_X2M_A12TR (
	R, 
	QN, 
	D, 
	CK);
   input R;
   output QN;
   input D;
   input CK;
endmodule

module DFFRPQN_X1M_A12TR (
	R, 
	QN, 
	D, 
	CK);
   input R;
   output QN;
   input D;
   input CK;
endmodule

module DFFRPQN_X0P5M_A12TR (
	R, 
	QN, 
	D, 
	CK);
   input R;
   output QN;
   input D;
   input CK;
endmodule

module DFFNSRPQ_X1M_A12TR (
	SN, 
	R, 
	Q, 
	D, 
	CKN);
   input SN;
   input R;
   output Q;
   input D;
   input CKN;
endmodule

module CGENI_X2M_A12TR (
	CON, 
	CI, 
	B, 
	A);
   output CON;
   input CI;
   input B;
   input A;
endmodule

module CGENCIN_X2M_A12TR (
	CO, 
	CIN, 
	B, 
	A);
   output CO;
   input CIN;
   input B;
   input A;
endmodule

module BUF_X9M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X7P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X6M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X6B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X5B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X4M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X4B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X3P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X3P5B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X3M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X3B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X2P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X2P5B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X2B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X1P7M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X1P7B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X1M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X1B_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X16M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X13M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X11M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUF_X0P8M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X9M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X7P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X6M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X4M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X3P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X3M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X2P5M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X1P7M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X1P2M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X1M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X16M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X11M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BUFH_X0P7M_A12TR (
	Y, 
	A);
   output Y;
   input A;
endmodule

module BITIE6_A12TR ();
endmodule

module AOI2XB1_X4M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module AOI2XB1_X3M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module AOI2XB1_X2M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module AOI2XB1_X1M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module AOI2XB1_X0P5M_A12TR (
	Y, 
	B0, 
	A1N, 
	A0);
   output Y;
   input B0;
   input A1N;
   input A0;
endmodule

module AOI22_X3M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI22_X2M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI22_X1P4M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI22_X1M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI22_X0P7M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI22_X0P5M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI222_X1M_A12TR (
	Y, 
	C1, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C1;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI222_X0P5M_A12TR (
	Y, 
	C1, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C1;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI221_X2M_A12TR (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI221_X1P4M_A12TR (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI221_X1M_A12TR (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI221_X0P7M_A12TR (
	Y, 
	C0, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AOI21_X3M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module AOI21_X2M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module AOI21_X1P4M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module AOI21_X1M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module AOI211_X2M_A12TR (
	Y, 
	C0, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B0;
   input A1;
   input A0;
endmodule

module AOI211_X1M_A12TR (
	Y, 
	C0, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B0;
   input A1;
   input A0;
endmodule

module AO22_X1P4M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AO22_X1M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AO22_X0P7M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AO22_X0P5M_A12TR (
	Y, 
	B1, 
	B0, 
	A1, 
	A0);
   output Y;
   input B1;
   input B0;
   input A1;
   input A0;
endmodule

module AO21_X1M_A12TR (
	Y, 
	B0, 
	A1, 
	A0);
   output Y;
   input B0;
   input A1;
   input A0;
endmodule

module AO21B_X4M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module AO21B_X3M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module AO21B_X2M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module AO21B_X1P4M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module AO21B_X1M_A12TR (
	Y, 
	B0N, 
	A1, 
	A0);
   output Y;
   input B0N;
   input A1;
   input A0;
endmodule

module AO21A1AI2_X2M_A12TR (
	Y, 
	C0, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B0;
   input A1;
   input A0;
endmodule

module AO21A1AI2_X1P4M_A12TR (
	Y, 
	C0, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B0;
   input A1;
   input A0;
endmodule

module AO21A1AI2_X1M_A12TR (
	Y, 
	C0, 
	B0, 
	A1, 
	A0);
   output Y;
   input C0;
   input B0;
   input A1;
   input A0;
endmodule

module AND4_X1M_A12TR (
	Y, 
	D, 
	C, 
	B, 
	A);
   output Y;
   input D;
   input C;
   input B;
   input A;
endmodule

module AND3_X1P4M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module AND3_X1M_A12TR (
	Y, 
	C, 
	B, 
	A);
   output Y;
   input C;
   input B;
   input A;
endmodule

module AND2_X8M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X6M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X3M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X2M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X1P4M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X1M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X11M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module AND2_X0P7M_A12TR (
	Y, 
	B, 
	A);
   output Y;
   input B;
   input A;
endmodule

module ADDH_X2M_A12TR (
	S, 
	CO, 
	B, 
	A);
   output S;
   output CO;
   input B;
   input A;
endmodule

module ADDH_X1P4M_A12TR (
	S, 
	CO, 
	B, 
	A);
   output S;
   output CO;
   input B;
   input A;
endmodule

module ADDH_X1M_A12TR (
	S, 
	CO, 
	B, 
	A);
   output S;
   output CO;
   input B;
   input A;
endmodule

module ADDF_X2M_A12TR (
	S, 
	CO, 
	CI, 
	B, 
	A);
   output S;
   output CO;
   input CI;
   input B;
   input A;
endmodule

module ADDF_X1P4M_A12TR (
	S, 
	CO, 
	CI, 
	B, 
	A);
   output S;
   output CO;
   input CI;
   input B;
   input A;
endmodule

module ADDF_X1M_A12TR (
	S, 
	CO, 
	CI, 
	B, 
	A);
   output S;
   output CO;
   input CI;
   input B;
   input A;
endmodule

module ADDFH_X2M_A12TR (
	SUM, 
	CO, 
	CI, 
	B, 
	A);
   output SUM;
   output CO;
   input CI;
   input B;
   input A;
endmodule

